MODEL_PARAMS = \
{ 'aggregationInfo': { 'days': 0,
                       'fields': [],
                       'hours': 0,
                       'microseconds': 0,
                       'milliseconds': 0,
                       'minutes': 0,
                       'months': 0,
                       'seconds': 0,
                       'weeks': 0,
                       'years': 0},
  'model': 'HTMPrediction',
  'modelParams': { 'anomalyParams': { u'anomalyCacheRecords': None,
                                      u'autoDetectThreshold': None,
                                      u'autoDetectWaitRecords': None},
                   'clParams': { 'alpha': 0.04997538384508139,
                                 'regionName': 'SDRClassifierRegion',
                                 'steps': '7',
                                 'verbosity': 0},
                   'inferenceType': 'TemporalAnomaly',
                   'sensorParams': { 'encoders': { u'AGE_0_54': None,
                                                   u'Ct': { 'clipInput': True,
                                                            'fieldname': 'Ct',
                                                            'maxval': 1.0,
                                                            'minval': 0,
                                                            'n': 41,
                                                            'name': 'Ct',
                                                            'type': 'ScalarEncoder',
                                                            'w': 21},
                                                   u'ZIP_10467': { 'clipInput': True,
                                                                   'fieldname': 'ZIP_10467',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'ZIP_10467',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'ZIP_10462': { 'clipInput': True,
                                                                   'fieldname': 'ZIP_10462',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'ZIP_10462',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'ZIP_10475': { 'clipInput': True,
                                                                   'fieldname': 'ZIP_10475',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'ZIP_10475',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'ZIP_10466': { 'clipInput': True,
                                                                   'fieldname': 'ZIP_10466',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'ZIP_10466',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'ZIP_10469': { 'clipInput': True,
                                                                   'fieldname': 'ZIP_10469',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'ZIP_10469',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DEPT_11': { 'clipInput': True,
                                                                   'fieldname': 'DEPT_11',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DEPT_11',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DEPT_24': { 'clipInput': True,
                                                                   'fieldname': 'DEPT_24',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DEPT_24',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DEPT_41': { 'clipInput': True,
                                                                   'fieldname': 'DEPT_41',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DEPT_41',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DEPT_34': { 'clipInput': True,
                                                                   'fieldname': 'DEPT_34',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DEPT_34',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DEPT_31': { 'clipInput': True,
                                                                   'fieldname': 'DEPT_31',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DEPT_31',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DEPT_60': { 'clipInput': True,
                                                                   'fieldname': 'DEPT_60',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DEPT_60',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'AGE_0_9': { 'clipInput': True,
                                                                   'fieldname': 'AGE_0_9',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'AGE_0_9',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'AGE_10_19': { 'clipInput': True,
                                                                   'fieldname': 'AGE_10_19',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'AGE_10_19',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'AGE_20_29': { 'clipInput': True,
                                                                   'fieldname': 'AGE_20_29',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'AGE_20_29',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'AGE_30_39': { 'clipInput': True,
                                                                   'fieldname': 'AGE_30_39',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'AGE_30_39',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'AGE_40_49': { 'clipInput': True,
                                                                   'fieldname': 'AGE_40_49',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'AGE_40_49',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'AGE_50_59': { 'clipInput': True,
                                                                   'fieldname': 'AGE_50_59',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'AGE_50_59',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'AGE_60_69': { 'clipInput': True,
                                                                   'fieldname': 'AGE_60_69',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'AGE_60_69',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'AGE_70_79': { 'clipInput': True,
                                                                   'fieldname': 'AGE_70_79',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'AGE_70_79',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'AGE_80_89': { 'clipInput': True,
                                                                   'fieldname': 'AGE_80_89',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'AGE_80_89',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'AGE_90_99': { 'clipInput': True,
                                                                   'fieldname': 'AGE_90_99',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'AGE_90_99',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DIST_1_7': { 'clipInput': True,
                                                                   'fieldname': 'DIST_1_7',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DIST_1_7',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DIST_8_14': { 'clipInput': True,
                                                                   'fieldname': 'DIST_8_14',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DIST_8_14',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DIST_15_21': { 'clipInput': True,
                                                                   'fieldname': 'DIST_15_21',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DIST_15_21',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DIST_22_28': { 'clipInput': True,
                                                                   'fieldname': 'DIST_22_28',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DIST_22_28',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DIST_29_35': { 'clipInput': True,
                                                                   'fieldname': 'DIST_29_35',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DIST_29_35',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DIST_36_42': { 'clipInput': True,
                                                                   'fieldname': 'DIST_36_42',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DIST_36_42',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DIST_43_49': { 'clipInput': True,
                                                                   'fieldname': 'DIST_43_49',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DIST_43_49',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DIST_50_56': { 'clipInput': True,
                                                                   'fieldname': 'DIST_50_56',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DIST_50_56',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DIST_57_63': { 'clipInput': True,
                                                                   'fieldname': 'DIST_57_63',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DIST_57_63',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'DIST_64_70': { 'clipInput': True,
                                                                   'fieldname': 'DIST_64_70',
                                                                   'maxval': 1.0,
                                                                   'minval': 0,
                                                                   'n': 54,
                                                                   'name': 'DIST_64_70',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'timestamp_dayOfWeek': None,
                                                   u'timestamp_timeOfDay': None,
                                                   u'timestamp_weekend': { 'fieldname': 'timestamp',
                                                                           'name': 'timestamp',
                                                                           'type': 'DateEncoder',
                                                                           'weekend': ( 21,
                                                                                        1)}},
                                     'sensorAutoReset': None,
                                     'verbosity': 0},
                   'spEnable': True,
                   'spParams': { 'boostStrength': 0.0,
                                 'columnCount': 2048,
                                 'globalInhibition': 1,
                                 'inputWidth': 0,
                                 'numActiveColumnsPerInhArea': 40,
                                 'potentialPct': 0.8,
                                 'seed': 1956,
                                 'spVerbosity': 0,
                                 'spatialImp': 'cpp',
                                 'synPermActiveInc': 0.05,
                                 'synPermConnected': 0.1,
                                 'synPermInactiveDec': 0.06811521904926},
                   'tmEnable': True,
                   'tmParams': { 'activationThreshold': 16,
                                 'cellsPerColumn': 32,
                                 'columnCount': 2048,
                                 'globalDecay': 0.0,
                                 'initialPerm': 0.21,
                                 'inputWidth': 2048,
                                 'maxAge': 0,
                                 'maxSegmentsPerCell': 128,
                                 'maxSynapsesPerSegment': 32,
                                 'minThreshold': 9,
                                 'newSynapseCount': 20,
                                 'outputType': 'normal',
                                 'pamLength': 5,
                                 'permanenceDec': 0.1,
                                 'permanenceInc': 0.1,
                                 'seed': 1960,
                                 'temporalImp': 'cpp',
                                 'verbosity': 0},
                   'trainSPNetOnlyIfRequested': False},
  'predictAheadTime': None,
  'version': 1}