# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2013, Numenta, Inc.  Unless you have an agreement
# with Numenta, Inc., for a separate license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero Public License for more details.
#
# You should have received a copy of the GNU Affero Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------


## This file defines parameters for a prediction experiment.

###############################################################################
#                                IMPORTANT!!!
# This params file is dynamically generated by the RunExperimentPermutations
# script. Any changes made manually will be over-written the next time
# RunExperimentPermutations is run!!!
###############################################################################


from nupic.frameworks.opf.expdescriptionhelpers import importBaseDescription

# the sub-experiment configuration
config ={
  'aggregationInfo' : {'seconds': 0, 'fields': [], 'months': 0, 'days': 0, 'years': 0, 'hours': 0, 'microseconds': 0, 'weeks': 0, 'minutes': 0, 'milliseconds': 0},
  'modelParams' : {'sensorParams': {'encoders': {'_classifierInput': {'maxval': 24000, 'classifierOnly': True, 'minval': 0, 'clipInput': True, 'n': 70, 'fieldname': 'Ct', 'w': 21, 'type': 'ScalarEncoder'}, u'NxtHol': None, u'timestamp_dayOfWeek': {'dayOfWeek': (21, 1), 'name': 'timestamp', 'fieldname': 'timestamp', 'type': 'DateEncoder'}, u'timestamp_timeOfDay': {'name': 'timestamp', 'fieldname': 'timestamp', 'timeOfDay': (21, 1.243054168557335), 'type': 'DateEncoder'}, u'Ct': {'maxval': 24000, 'name': 'Ct', 'clipInput': True, 'minval': 0, 'n': 139, 'fieldname': 'Ct', 'w': 21, 'type': 'ScalarEncoder'}, u'timestamp_weekend': None}}, 'spParams': {'synPermInactiveDec': 0.03769285614096052}, 'tpParams': {'minThreshold': 11, 'activationThreshold': 16, 'pamLength': 4}, 'clParams': {'alpha': 0.08568919879429909}},

}

mod = importBaseDescription('..\description.py', config)
locals().update(mod.__dict__)
